language: node_js
node_js:
  - "10"

cache: npm

install: 
  - npm install

script:
  - npm run lint
  - npm run test
 
before_deploy:
  - npm run build
  - cd dist
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: master
    tags: true